version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd app
      - npm install
      - cd ../server
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - cd server
      - node index
      - cd ../app
      - npm run test
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - server/**/*
    - app/src/index.js
    - app/src/app.js
    - app/package.json
    - node_modules/**/*
